# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: >
 Application Infrastructure - AppSync Stack

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
  CustomerId:
    Default: orb
    Type: String
  ProjectId:
    Default: integration-hub
    Type: String
  TracingIs:
    Default: Active
    Type: String

# --------------------------------------------------- #
Resources:
  IntegrationHubApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync'
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        UserPoolId: !Sub "${CustomerId}-${ProjectId}-${Environment}-cognito-user-pool-id"
        AwsRegion: !Ref AWS::Region
        DefaultAction: ALLOW
      AdditionalAuthenticationProviders:
        - AuthenticationType: API_KEY
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt AppSyncLoggingServiceRole.Arn
        FieldLogLevel: ALL
        ExcludeVerboseContent: false
  IntegrationHubApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Description: "API Key for unauthenticated access"
      Expires: 1735603200
  ApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${CustomerId}-${ProjectId}-${Environment}-appsync-graphql-key'
      Description: "AppSync API Key for unauthenticated access"
      SecretString: !GetAtt IntegrationHubApiKey.ApiKey
  IntegrationHubSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Definition: |
        
        type SMSVerificationResponse @aws_api_key @aws_cognito_user_pools{
          status_code: Float!
          message: String
          code: Float
        }
        
        input SMSVerificationInput @aws_api_key @aws_cognito_user_pools{
          phone_number: String!
        }
        
        enum UserStatus @aws_api_key @aws_cognito_user_pools{
          ACTIVE
          PENDING
          SUSPENDED
          INACTIVE
        }
        enum UserGroup @aws_api_key @aws_cognito_user_pools{
          USER
          CUSTOMER
          CLIENT
          EMPLOYEE
          OWNER
        }

        type User @aws_api_key @aws_cognito_user_pools{
          id: String!
          cognito_id: String!
          email: String!
          phone_number: String
          first_name: String
          last_name: String
          groups: [UserGroup!]!
          status: UserStatus!
          created_at: String!
        }

        input UserQueryInput @aws_api_key @aws_cognito_user_pools{
          id: String
          cognito_id: String
          email: String
        }
        
        input UserCreateInput @aws_api_key @aws_cognito_user_pools{
          id: String!
          cognito_id: String!
          email: String!
          groups: [UserGroup!]!
          status: UserStatus!
          created_at: String!
        }
        
        input UserUpdateInput @aws_api_key @aws_cognito_user_pools{
          email: String
          phone_number: String
          first_name: String
          last_name: String
          groups: [UserGroup!]
          status: UserStatus
        }
        
        type UserResponse @aws_api_key @aws_cognito_user_pools{
          status_code: Float!
          message: String
          user: User
        }
  
        type Mutation {
          sendSMSVerificationCode(input: SMSVerificationInput!): SMSVerificationResponse! @aws_cognito_user_pools
          userCreate(input: UserCreateInput!): UserResponse! @aws_api_key @aws_cognito_user_pools 
          userUpdate(input: UserUpdateInput!): UserResponse! @aws_cognito_user_pools
        }
  
        type Query {
          userQueryById(input: UserQueryInput!): UserResponse! @aws_api_key
        }
    
        schema {
          query: Query
          mutation: Mutation
        }


  # Data Sources
  SMSVerificationDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: SMSVerificationDataSource
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-sms-verification-lambda-arn}}'
  UsersDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      Name: UsersDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      DynamoDBConfig:
          TableName: !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-users-table-name}}'
          AwsRegion: !Ref AWS::Region

  # --------------------------------------------------- #
  # Resolvers                                           #
  # --------------------------------------------------- #

  # User Resolvers
  UserCreateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: IntegrationHubSchema
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: userCreate
      DataSourceName: !GetAtt UsersDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "PutItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.input.id)
          },
          "attributeValues": $util.dynamodb.toMapValues($ctx.args.input)
        }
      ResponseMappingTemplate: |
        #if($ctx.error)
          $util.error($ctx.error.message, $ctx.error.type)
        #end
        
        #set($response = {
          "status_code": 200,
          "message": "User updated successfully",
          "user": $ctx.args.input
        })
        
        $util.toJson($response)
  UserQueryByIdResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: IntegrationHubSchema
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Query
      FieldName: userQueryById
      DataSourceName: !GetAtt UsersDataSource.Name
      RequestMappingTemplate: |
        #set($ids = {})
        #if($ctx.args.input.id)
          $util.qr($ids.put("id", $ctx.args.input.id))
        #end
        #if($ctx.args.input.cognito_id && !$ids.id)
          $util.qr($ids.put("cognito_id", $ctx.args.input.cognito_id))
        #end
        #if($ctx.args.input.email && !$ids.id && !$ids.cognito_id)
          $util.qr($ids.put("email", $ctx.args.input.email))
        #end
        
        #if($ids.isEmpty())
          $util.error("At least one identifier (id, cognito_id, or email) must be provided")
        #end
        
        #if($ids.id)
          {
            "version": "2017-02-28",
            "operation": "GetItem",
            "key": {
              "id": $util.dynamodb.toDynamoDBJson($ids.id)
            }
          }
        #elseif($ids.cognito_id)
          {
            "version": "2017-02-28",
            "operation": "Query",
            "index": "cognito_id-index",
            "query": {
              "expression": "cognito_id = :cognitoId",
              "expressionValues": {
                ":cognitoId": $util.dynamodb.toDynamoDBJson($ids.cognito_id)
              }
            }
          }
        #else
          {
            "version": "2017-02-28",
            "operation": "Query",
            "index": "email-index",
            "query": {
              "expression": "email = :email",
              "expressionValues": {
                ":email": $util.dynamodb.toDynamoDBJson($ids.email)
              }
            }
          }
        #end
      ResponseMappingTemplate: |
        #if($ctx.error)
          $util.error($ctx.error.message, $ctx.error.type)
        #end
  
        #set($response = {
          "status_code": 200,
          "user": {}
        })
  
        #if($ctx.result.items)
          #if($ctx.result.items.size() == 0)
            #set($response.status_code = 404)
            $util.qr($response.put("user", null))
          #else
            #set($response.user = $ctx.result.items[0])
          #end
        #else
          #if($ctx.result)
            #set($response.user = $ctx.result)
          #else
            #set($response.status_code = 404)
            $util.qr($response.put("user", null))
          #end
        #end
        
        $util.toJson($response)

  UserUpdateResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: IntegrationHubSchema
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: userUpdate
      DataSourceName: !GetAtt UsersDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "UpdateItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.input.id)
          },
          "attributeValues": $util.toJson($ctx.args.input)
        }
      ResponseMappingTemplate: |
        #if($ctx.error)
          $util.error($ctx.error.message, $ctx.error.type)
        #end
        
        #set($response = {
          "status_code": 200,
          "message": "User updated successfully",
          "user": $ctx.args.input
        })
        
        $util.toJson($response)

  # SMS Verification Resolvers
  SendSMSVerificationCodeResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: IntegrationHubSchema
    Properties:
      ApiId: !GetAtt IntegrationHubApi.ApiId
      TypeName: Mutation
      FieldName: sendSMSVerificationCode
      DataSourceName: !GetAtt SMSVerificationDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "Invoke",
          "payload": $util.toJson($context.arguments)
        }
      ResponseMappingTemplate: |
        $util.toJson($context.result)




  # IAM
  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppSyncServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub '{{resolve:ssm:${CustomerId}-${ProjectId}-${Environment}-sms-verification-lambda-arn}}'
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:PutItem
                Resource:
                  # Add base table ARNs
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CustomerId}-${ProjectId}-${Environment}-users'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CustomerId}-${ProjectId}-${Environment}-user-profiles'
                  # Add GSI ARNs
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CustomerId}-${ProjectId}-${Environment}-users/index/*'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${CustomerId}-${ProjectId}-${Environment}-user-profiles/index/*'
  AppSyncLoggingServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppSyncLoggingServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/appsync/apis/*:*'

# --------------------------------------------------- #
Outputs:
  GraphQLApiUrl:
    Description: 'URL of the AppSync GraphQL API'
    Value: !GetAtt IntegrationHubApi.GraphQLUrl
  GraphQLApiKeySecretName:
    Description: 'Name of the Secret containing the AppSync API Key'
    Value: !Ref ApiKeySecret
