# --------------------------------------------------- #
AWSTemplateFormatVersion: 2010-09-09

# --------------------------------------------------- #
Transform: AWS::Serverless-2016-10-31

# --------------------------------------------------- #
Description: Application Infrastructure

# --------------------------------------------------- #
Parameters:
  Environment:
    Default: dev
    Type: String
  CustomerId:
    Default: orb
    Type: String
  ProjectId:
    Default: integration-hub
    Type: String
  TracingIs:
    Default: Active
    Type: String

# --------------------------------------------------- #
Resources:

  # Applications Table
  ApplicationsTable:
    Properties:
      AttributeDefinitions:
        -
          AttributeName: application_id
          AttributeType: S
        -
          AttributeName: user_id
          AttributeType: S
        -
          AttributeName: environment
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: application_id
          KeyType: HASH
        -
          AttributeName: environment
          KeyType: RANGE
      GlobalSecondaryIndexes:
        -
          IndexName: user-id-index
          KeySchema:
            -
              AttributeName: user_id
              KeyType: HASH
            -
              AttributeName: application_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName: !Sub "${CustomerId}-${ProjectId}-${Environment}-applications"
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId
    Type: AWS::DynamoDB::Table

  # Application User Roles Table
  ApplicationUsersTable:
    Properties:
      AttributeDefinitions:
        -
          AttributeName: application_id
          AttributeType: S
        -
          AttributeName: user_id
          AttributeType: S
        -
          AttributeName: environment
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: application_id
          KeyType: HASH
        -
          AttributeName: user_id
          KeyType: RANGE
      TableName: !Sub "${CustomerId}-${ProjectId}-${Environment}-application-users"
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId
    Type: AWS::DynamoDB::Table

  # Users Table
  UsersTable:
    Properties:
      AttributeDefinitions:
        -
          AttributeName: user_id
          AttributeType: S
        -
          AttributeName: cognito_id
          AttributeType: S
        -
          AttributeName: email
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        -
          IndexName: cognito-id-index
          KeySchema:
            -
              AttributeName: cognito_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        -
          IndexName: email-index
          KeySchema:
            -
              AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TableName: !Sub "${CustomerId}-${ProjectId}-${Environment}-users"
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId
    Type: AWS::DynamoDB::Table
  UserProfilesTable:
    Properties:
      AttributeDefinitions:
        -
          AttributeName: user_id
          AttributeType: S
        -
          AttributeName: email
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH
        -
          AttributeName: email
          KeyType: RANGE
      GlobalSecondaryIndexes:
        -
          IndexName: email-index
          KeySchema:
            -
              AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TableName: !Sub "${CustomerId}-${ProjectId}-${Environment}-user-profiles"
      Tags:
        - Key: Billable
          Value: "true"
        - Key: CustomerId
          Value: !Ref CustomerId
        - Key: Environment
          Value: !Ref Environment
        - Key: ProjectId
          Value: !Ref ProjectId
    Type: AWS::DynamoDB::Table

  # Parameter Store
  UsersTableNameParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-users-table-name"
      Type: String
      Value: !Ref UsersTable
      Description: DynamoDB Users Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter
  UsersTableArnParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-users-table-arn"
      Type: String
      Value: !GetAtt UsersTable.Arn
      Description: DynamoDB Users Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter
  UserProfilesTableNameParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-user-profiles-table-name"
      Type: String
      Value: !Ref UserProfilesTable
      Description: DynamoDB User Profiles Table Name
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter
  UserProfilesTableArnParameter:
    Properties:
      Name: !Sub "${CustomerId}-${ProjectId}-${Environment}-user-profiles-table-arn"
      Type: String
      Value: !GetAtt UserProfilesTable.Arn
      Description: DynamoDB User Profiles Table Arn
      Tags:
        Billable: true
        CustomerId: !Ref CustomerId
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
    Type: AWS::SSM::Parameter
