name: deploy-backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - 'dev'
          - 'prod'
      region:
        description: 'AWS Region'
        required: true
        type: choice
        options:
          - 'us-east-1'
      customer_id:
        description: 'Customer ID'
        required: true
        type: string
        default: 'orb'
      project_id:
        description: 'Project ID'
        required: true
        type: string
        default: 'integration-hub'

jobs:
  deploy-backend-stacks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Python environment
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Fetch AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      env:
        ENVIRONMENT: ${{ inputs.environment }}

    # Bootstrap
    - name: Deploy Bootstrap Stack
      run: |
        sam build --template bootstrap.yml
        sam package --template-file bootstrap.yml --s3-bucket ${{vars.customer_id}}-${{vars.project_id}}-build-artifacts --output-template-file bootstrap-packaged.yml
        sam deploy --template-file bootstrap-packaged.yml --s3-bucket ${{vars.customer_id}}-${{vars.project_id}}-build-artifacts --stack-name ${{vars.customer_id}}-${{vars.project_id}}-bootstrap --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
        aws s3 cp bootstrap-packaged.yml s3://${{vars.customer_id}}-${{vars.project_id}}-build-templates/bootstrap-packaged.yml
      working-directory: ./infrastructure/cloudformation
      env:
        ENVIRONMENT: ${{ inputs.environment }}

    # Cognito
    - name: Deploy Cognito Stack
      run: |
        sam build --template cognito.yml
        sam package --template-file cognito.yml --s3-bucket ${{vars.customer_id}}-${{vars.project_id}}-build-artifacts --output-template-file cognito-packaged.yml
        sam deploy --template-file cognito-packaged.yml --s3-bucket ${{vars.customer_id}}-${{vars.project_id}}-build-artifacts --stack-name ${{vars.customer_id}}-${{vars.project_id}}-cognito --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
        aws s3 cp cognito-packaged.yml s3://${{vars.customer_id}}-${{vars.project_id}}-build-templates/cognito-packaged.yml
      working-directory: ./infrastructure/cloudformation
      env:
        ENVIRONMENT: ${{ inputs.environment }}

    # DynamoDb
    - name: Deploy DynamoDb Stack
      run: |
        sam build \
          --template dynamodb.yml
        sam package \
          --template-file dynamodb.yml \
          --s3-bucket ${{vars.customer_id}}-${{vars.project_id}}-build-artifacts \
          --output-template-file dynamodb-packaged.yml
        sam deploy \
          --template-file dynamodb-packaged.yml \
          --s3-bucket ${{vars.customer_id}}-${{vars.project_id}}-build-artifacts \
          --stack-name ${{vars.customer_id}}-${{vars.project_id}}-dynamodb \
          --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
        aws s3 cp dynamodb-packaged.yml \
          s3://${{vars.customer_id}}-${{vars.project_id}}-build-templates/dynamodb-packaged.yml

      working-directory: ./infrastructure/cloudformation
      env:
        ENVIRONMENT: ${{ inputs.environment }}

    # Lambdas
    - name: Deploy Lambda Stack
      run: |
        sam build \
          --template dynamodb.yml
        sam package \
          --template-file lambdas.yml \
          --s3-bucket ${{vars.customer_id}}-${{vars.project_id}}-build-artifacts \
          --output-template-file lambdas-packaged.yml
        
        sam deploy \
          --template-file lambdas-packaged.yml \
          --s3-bucket ${{vars.customer_id}}-${{vars.project_id}}-build-artifacts \
          --stack-name orb-integration-hub-lambdas \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset
        
        aws s3 cp lambdas-packaged.yml \
          s3://${{vars.customer_id}}-${{vars.project_id}}-build-templates/lambdas-packaged.yml

      working-directory: ./infrastructure/cloudformation
      env:
        ENVIRONMENT: ${{ inputs.environment }}

    # Appsync
    - name: Deploy Appsync Stack
      run: |
        sam build \
          --template appsync.yml

        sam package \
          --template-file appsync.yml \
          --s3-bucket ${{vars.customer_id}}-${{vars.project_id}}-build-artifacts \
          --output-template-file appsync-packaged.yml

        sam deploy \
          --template-file appsync-packaged.yml \
          --s3-bucket ${{vars.customer_id}}-${{vars.project_id}}-build-artifacts \
          --stack-name ${{vars.customer_id}}-${{vars.project_id}}-appsync  \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset

        aws s3 cp appsync-packaged.yml \
          s3://${{vars.customer_id}}-${{vars.project_id}}-build-templates/appsync-packaged.yml

      working-directory: ./infrastructure/cloudformation
      env:
        ENVIRONMENT: ${{ inputs.environment }}
