name: generate-context

on:
  workflow_dispatch:

jobs:
  generate-context:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CONTEXT_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create output directory
        run: mkdir -p ./context_output

      - name: Run context generator
        run: python .github/scripts/context_generator.py
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          OUTPUT_DIR: './context_output'

      - name: Upload context files
        uses: actions/upload-artifact@v3
        with:
          name: project-context
          path: |
            context_output/claude_context.json
            context_output/context_summary.md

      - name: Update context branch
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -B context-updates
          mkdir -p docs/context
          cp -r context_output/* docs/context/
          git add docs/context/
          git commit -m "Update AI context files" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push -f origin context-updates
        env:
          GITHUB_TOKEN: ${{ secrets.CONTEXT_PAT }}